### ISSUE TITLE
add ability to hide/disable graph on mobile?

### ISSUE THREAD

**Issue by jsifalda** [ras0q/obsidian-graph-banner#102]
on mobile it just do no work with my workflow and it  kinda clutter my notes…
would be possible to add option to disable it on mobile devices please?

george

**Comment by ras0q** [comment]
Thanks for the feature request!

As a workaround for now, try the following solutions.

1. Disable this plugin only on mobile devices.
  - If the list of active plugins is shared, "Plugin Groups" should be beneficial.
2. Custom CSS

```css
@media screen and (max-width: 600px) {
  .graph-banner-content {
    display: none;
  }
}
```
