### ISSUE TITLE
add a border to it

### ISSUE THREAD

**Issue by Dopairym** [ras0q/obsidian-graph-banner#116]
Title
It can be the accent color

**Comment by ras0q** [comment]
You can customize the banner's appearance! Add the following code to Appearance>CSS snippets to activate it.

```css
.graph-banner-content {
	border: 2px solid var(--color-accent);
}
```
