### ISSUE TITLE
[Feature Request] Add Customizable Graph Position Options and Visibility Toggle for Enhanced Visualization

### ISSUE THREAD

**Issue by PandaNocturne** [ras0q/obsidian-graph-banner#40]
Thank you for your work on this plugin. It has been extremely helpful for Obsidian's local graph feature.However, I would like to move the graph to the top right corner of the note interface, similar to the publish layout.

Here is a small adjustment I made to your Styles.css file:

![PixPin_2024-06-22_00-55-22](https://github.com/ras0q/obsidian-graph-banner/assets/84729049/f8a0ce91-1a9f-4829-b8e7-a07dbd8f0832)

```css
/* https://github.com/mgmeyers/obsidian-style-settings */
/* @settings
name: Graph Banner
id: graph-banner
settings:
  - id: hide-graph-banner
    title: Hide Graph Banner
    type: class-toggle
    addCommand: true
  - id: graph-banner-type-select
    title: Select graph type
    type: class-select
    allowEmpty: false
    default: banner-graph
    options:
      - banner-graph
      - hanging-graph
  - id: banner-height
    title: Banner Height
    description: The height of the banner. (e.g. 20vh, 200px)
    type: variable-text
    default: 20vh
  - id: banner-width
    title: Banner Width
    description: The width of the banner. (e.g. 20vh, 200px)
    type: variable-text
    default: 400px
*/

body {
  --banner-height: 20vh;
  --banner-width: 400px;
}

body.hide-graph-banner .graph-banner-content {
  display: none !important;
}

.banner-graph .graph-banner-content {
  width: auto;
  height: var(--banner-height);
  margin-bottom: 16px;
}

.hanging-graph .cm-sizer>div.view-content.graph-banner-content,
.hanging-graph .mod-header>div.view-content.graph-banner-content {
  display: block;
  position: fixed !important;
  right: 50px;
  top: 50px;
  z-index: 2;

  border-radius: 10px;
  border: 1px solid var(--background-modifier-border);
  width: var(--banner-width);
  height: var(--banner-height);
  margin-bottom: 16px;
}
```

I added two types of graph display modes:
1. **banner-graph** - retains the original display.
2. **hanging-graph** - positions the graph at the top-right corner of the note interface.

Additionally, I also added a CSS class toggle control using the Style Settings plugin to manage the visibility of the graph banner. The .hide-graph-banner class can be toggled using Obsidian commands, which could be useful with the Commander plugin.

I'd love it if you could consider adding this CSS modification to your plugin. I think it would offer an even richer visualization experience. Thanks again for all your hard work on this plugin!
