### ISSUE TITLE
[FR] Hover to expand the graph?

### ISSUE THREAD

**Issue by Moyf** [ras0q/obsidian-graph-banner#57]
Hey! I tried to use css to add `:hover()` property:
```css

.view-content.graph-banner-content:hover {
    max-height: 300px;
    transition: all 0.2s;
}
```

But I found that the canvas doesn't expand:
![demo](https://github.com/user-attachments/assets/91b122ee-55ba-4dc2-b082-c53fbaec8d3e)

Is there some way to expand the Canvas with the container (or make the canvas height bigger than 100% ?)
